# Generated by Django 3.2.2 on 2021-05-13 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relief', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='RequestHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200)),
                ('twitter_handle', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.TextField()),
                ('help_offered', models.CharField(choices=[('medicines', 'Medicines'), ('hospital', 'Hospital'), ('oxygen', 'Oxygen'), ('food', 'Food'), ('ambulance', 'Ambulance'), ('blood', 'Blood/Plasma'), ('other', 'Other')], default='oxygen', max_length=20)),
                ('address', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('verified_on', models.DateTimeField(auto_now=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
