# Generated by Django 3.2.2 on 2021-05-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relief', '0002_auto_20210513_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesthelp',
            name='mobile_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requesthelp',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
