# Generated by Django 3.2.2 on 2021-05-13 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relief', '0003_auto_20210513_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesthelp',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='relief.state'),
        ),
    ]
