# Generated by Django 3.2.2 on 2021-05-13 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relief', '0004_requesthelp_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requesthelp',
            old_name='help_offered',
            new_name='help_needed',
        ),
    ]
