# Generated by Django 3.2.2 on 2021-05-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relief', '0005_rename_help_offered_requesthelp_help_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesthelp',
            name='assistance_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requesthelp',
            name='city',
            field=models.CharField(default='Delhi', max_length=200),
            preserve_default=False,
        ),
    ]
