# Generated by Django 3.2.2 on 2021-05-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relief', '0006_auto_20210513_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesthelp',
            name='mobile_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
