# Generated by Django 3.2.2 on 2021-05-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relief', '0007_alter_requesthelp_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesthelp',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requesthelp',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requesthelp',
            name='is_help_offered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requesthelp',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requesthelp',
            name='help_needed',
            field=models.CharField(choices=[('medicines', 'Medicines'), ('hospital', 'Hospital'), ('oxygen', 'Oxygen'), ('food', 'Food'), ('ambulance', 'Ambulance'), ('blood', 'Blood/Plasma'), ('financial', 'Financial'), ('other', 'Other')], default='oxygen', max_length=20),
        ),
    ]
