# Generated by Django 3.2.2 on 2021-05-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relief', '0009_auto_20210520_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesthelp',
            name='volunteers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
